services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    environment:
      - AUTOR=OmarV & JorgeM
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=notas
      - DB_USER=postgres
      - DB_PASS=1234
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: